"""Root conftest for pytest configuration and shared fixtures."""
import pytest
from tests.fixtures import (
    mock_subprocess,
    temp_output_dir,
    sample_scan_config,
    sample_scan_configs,
    sample_findings,
    mock_bbot_output,
    sample_openapi_spec,
    event_loop,
    bbot_server_instance,
    mock_async_scan,
    test_config,
    mock_process_factory,
    TestDataBuilder,
    pytest_configure,
    pytest_unconfigure,
)
from tests.utils import (
    MockSubprocessProcess,
    TestDataBuilder as UtilTestDataBuilder,
    AssertionMixin,
    IssueTracker,
    TestConfigBuilder,
    TestTracker,
    test_setup_teardown,
    temporary_directory,
    measure_execution_time,
    mock_execute_command,
    mock_execute_cmd,
    async_execute_mock,
    generate_test_findings,
    generate_test_modules,
    assert_contains,
    assert_dict_contains,
    assert_keys_equal,
)